title: LazyLock's Devlog
author: LazyLock
email: lazylock99@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  풀스택 개발과 데이터 분석을 공부중인 강동헌의 기술블로그입니다.
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Martin Hoffman
  subtitle: Web Developer & Data Scientist
  skills: with Python,  Node.js & Vue.js
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    naver: lazylock99
    github: lazylock
    linkedIn: in/동헌-강-926444252
    # rss: rss
  
  navigation:
    - title: Home
      url: "/"
    - title: Algorithm
      url: "algorithm"
    - title: Study
      url: "study"
    - title: Project
      url: "project"
  
  tage:
    - node.js
    - vue.js
    - javascript
    - python



# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

remote_theme: samarsault/texture

# theme: texture